[package]
name = "r2048"
version = "0.1.0"
authors = ["YeLi <i@yeli.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
log = "0.4.14"
log4rs = "1.0.0"
serde = "1.0.127"
serde_json = "*"
